version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${SF_POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  sserafimflowapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Database
      SF_SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${SF_POSTGRES_DB}?serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # AWS
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      SF_S3_BUCKET_NAME: ${SF_S3_BUCKET_NAME}
      # JWT
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXP_TIME: ${JWT_EXP_TIME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sserafimflowapp

volumes:
  postgres:
