server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

IS_PRODUCTION: true

FRONTEND_URL1: https://sserafimflow.vercel.app
FRONTEND_URL2: http://localhost:4200

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_EXP_TIME: ${JWT_EXP_TIME}

# Swagger: http://localhost:8080/swagger-ui/index.html
