server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sserafimflowdb
    username: postgres
    password: 40se02j7
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

IS_PRODUCTION: false
FRONTEND_URL: http://localhost:4200

SUNAT_TOKEN: apis-token-10610.12f-TXShrNHm3Defoy1qXoSC-tbZhLmo
